activation: tanh
adam_betas:
- 0.9
- 0.999
adam_eps: 1.0e-08
architecture:
- 2
- 40
- 80
- 80
- 80
- 80
- 80
- 40
- 2
batch_size: 512
bins: 5
cuda: true
epochs: 10000
eval_only: false
lbfgs_history_size: 20
lbfgs_line_search: strong_wolfe
lbfgs_lr: 1.0
lbfgs_max_iter: 20
lbfgs_tolerance_change: 1.0e-15
lbfgs_tolerance_grad: 1.0e-15
lr: 0.0001
n_boundary_eval: 20
n_boundary_train: 50
n_initial_eval: 20
n_initial_train: 50
n_residual_eval: 1000
n_residual_train: 20000
n_samples_ncc: 5000
name: linear_slope_less_params
ncc_eval_every: 3400
optimizer_switch_at: 0.9
print_every: 1000
problem: schrodinger
problem2:
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  spatial_dim: 1
  spatial_domain:
  - - 0.0
    - 1.0
  temporal_domain:
  - 0.0
  - 1.0
resume_from: null
save_every: 5000
schrodinger:
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  spatial_dim: 1
  spatial_domain:
  - - -5.0
    - 5.0
  temporal_domain:
  - 0.0
  - 1.5707963267948966
seed: 42
